version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: thermalens_db
    environment:
      - POSTGRES_USER=thermalens
      - POSTGRES_PASSWORD=thermalens_pass
      - POSTGRES_DB=thermalens
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgis_data:
