import React from 'react';
import { X, Sparkles, AlertTriangle, ShieldCheck, Sun, ArrowRight, Layers } from 'lucide-react';

interface FullBriefModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const FullBriefModal: React.FC<FullBriefModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-xs animate-in fade-in duration-200">
      <div className="bg-white border border-[#D5E3DB] shadow-2xl rounded-2xl max-w-xl w-full p-6 space-y-5">
        <div className="flex items-start justify-between gap-4 pb-3 border-b border-[#EAF2ED]">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-[#EAF5EE] text-[#164E35] flex items-center justify-center">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-base font-extrabold text-[#143624]">
                Today&apos;s Heat Intelligence Narrative
              </h2>
              <div className="text-xs text-[#5D7769]">
                Generated by Antigravity Predictive Engine · 06:42 AM IST
              </div>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-[#6B8576] hover:bg-[#F1F6F3] rounded-lg transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="space-y-3 text-xs text-[#3E5547] leading-relaxed">
          <p>
            Northern Chennai is experiencing extreme radiative forcing resulting from a combination of calm sea breezes and dense asphalt-to-canopy ratios (&lt; 5% green cover in Wards 12–18).
          </p>
          <p>
            Thermal lag models predict that peak ambient temperatures of <strong>38.7°C</strong> will occur at <strong>14:00</strong>, with localized Land Surface Temperatures (LST) reaching <strong>46.2°C</strong> across industrial metal roofing clusters.
          </p>
          <p>
            Unlike coastal wards where riparian estuaries moderate evening cooling, northern industrial tracts will maintain heat indices above 75 points until 21:00, creating high nocturnal cardiovascular stress.
          </p>
        </div>

        <div className="p-3 bg-[#F8FAF8] border border-[#E2EBE5] rounded-xl flex items-center justify-between text-xs">
          <span className="font-semibold text-[#164E35]">Action Status: Priority Dispatch</span>
          <span className="font-mono text-[#6B8576]">Advisory Level 3</span>
        </div>

        <div className="pt-2 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-[#164E35] hover:bg-[#113E2A] text-white text-xs font-bold transition-colors cursor-pointer"
          >
            Acknowledge & Close
          </button>
        </div>
      </div>
    </div>
  );
};
